--[[
	BallPlay Cupid
	Puzzle #04
	
	
	
	(c) Jeroen P. Broks, 2016, All rights reserved
	
		This program is free software: you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.
		
		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
		You should have received a copy of the GNU General Public License
		along with this program.  If not, see <http://www.gnu.org/licenses/>.
		
	Exceptions to the standard GNU license are available with Jeroen's written permission given prior 
	to the project the exceptions are needed for.
Version: 16.04.26
]]

  -- This file has been generated by BallPlay Cupid.
  -- and may only be used in combination with that game
  -- and in unmodified form. 
  -- unless stated otherwise in the game license.


local ret1, ret2



ret1 = {
	["format"] = {
		[2] = 15,
		[1] = 25
	             },
	["partime"] = 0,
	["obstacles"] = {
		[">10:2<"] = "a_exit",
		[">10:10<"] = "a_exit"
	                },
	["floors"] = {
		[">8:10<"] = "pz_floor_nature_untitled",
		[">4:1<"] = "pz_floor_nature_untitled",
		[">9:2<"] = "pz_floor_nature_untitled",
		[">3:11<"] = "pz_floor_nature_untitled",
		[">4:2<"] = "pz_floor_nature_untitled",
		[">1:4<"] = "pz_floor_nature_untitled",
		[">13:5<"] = "pz_floor_nature_untitled",
		[">16:1<"] = "pz_floor_nature_untitled",
		[">0:3<"] = "pz_floor_nature_untitled",
		[">4:0<"] = "pz_floor_nature_untitled",
		[">5:8<"] = "pz_floor_nature_untitled",
		[">8:4<"] = "pz_floor_nature_untitled",
		[">18:11<"] = "pz_floor_nature_untitled",
		[">1:0<"] = "pz_floor_nature_untitled",
		[">17:1<"] = "pz_floor_nature_untitled",
		[">8:11<"] = "pz_floor_nature_untitled",
		[">3:7<"] = "pz_floor_nature_untitled",
		[">0:8<"] = "pz_floor_nature_untitled",
		[">10:9<"] = "pz_floor_nature_untitled",
		[">8:6<"] = "pz_floor_nature_untitled",
		[">4:9<"] = "pz_floor_nature_untitled",
		[">13:9<"] = "pz_floor_nature_untitled",
		[">13:6<"] = "pz_floor_nature_untitled",
		[">16:7<"] = "pz_floor_nature_untitled",
		[">17:9<"] = "pz_floor_nature_untitled",
		[">2:1<"] = "pz_floor_nature_untitled",
		[">19:0<"] = "pz_floor_nature_untitled",
		[">11:11<"] = "pz_floor_nature_untitled",
		[">10:3<"] = "pz_floor_nature_untitled",
		[">0:10<"] = "pz_floor_nature_untitled",
		[">8:0<"] = "pz_floor_nature_untitled",
		[">0:2<"] = "pz_floor_nature_untitled",
		[">0:4<"] = "pz_floor_nature_untitled",
		[">2:3<"] = "pz_floor_nature_untitled",
		[">4:11<"] = "pz_floor_nature_untitled",
		[">7:7<"] = "pz_floor_nature_untitled",
		[">20:12<"] = "pz_floor_nature_untitled",
		[">1:1<"] = "pz_floor_nature_untitled",
		[">2:10<"] = "pz_floor_nature_untitled",
		[">2:12<"] = "pz_floor_nature_untitled",
		[">10:4<"] = "pz_floor_nature_untitled",
		[">19:4<"] = "pz_floor_nature_untitled",
		[">8:2<"] = "pz_floor_nature_untitled",
		[">9:1<"] = "pz_floor_nature_untitled",
		[">17:8<"] = "pz_floor_nature_untitled",
		[">15:8<"] = "pz_floor_nature_untitled",
		[">9:7<"] = "pz_floor_nature_untitled",
		[">12:8<"] = "pz_floor_nature_untitled",
		[">15:3<"] = "pz_floor_nature_untitled",
		[">12:3<"] = "pz_floor_nature_untitled",
		[">7:4<"] = "pz_floor_nature_untitled",
		[">19:3<"] = "pz_floor_nature_untitled",
		[">11:10<"] = "pz_floor_nature_untitled",
		[">4:8<"] = "pz_floor_nature_untitled",
		[">0:0<"] = "pz_floor_nature_untitled",
		[">17:10<"] = "pz_floor_nature_untitled",
		[">5:4<"] = "pz_floor_nature_untitled",
		[">8:3<"] = "pz_floor_nature_untitled",
		[">1:3<"] = "pz_floor_nature_untitled",
		[">6:5<"] = "pz_floor_nature_untitled",
		[">0:9<"] = "pz_floor_nature_untitled",
		[">14:7<"] = "pz_floor_nature_untitled",
		[">19:8<"] = "pz_floor_nature_untitled",
		[">8:5<"] = "pz_floor_nature_untitled",
		[">20:0<"] = "pz_floor_nature_untitled",
		[">15:5<"] = "pz_floor_nature_untitled",
		[">11:8<"] = "pz_floor_nature_untitled",
		[">17:12<"] = "pz_floor_nature_untitled",
		[">2:0<"] = "pz_floor_nature_untitled",
		[">19:9<"] = "pz_floor_nature_untitled",
		[">6:8<"] = "pz_floor_nature_untitled",
		[">9:12<"] = "pz_floor_nature_untitled",
		[">11:12<"] = "pz_floor_nature_untitled",
		[">8:7<"] = "pz_floor_nature_untitled",
		[">11:5<"] = "pz_floor_nature_untitled",
		[">7:8<"] = "pz_floor_nature_untitled",
		[">16:9<"] = "pz_floor_nature_untitled",
		[">0:12<"] = "pz_floor_nature_untitled",
		[">17:11<"] = "pz_floor_nature_untitled",
		[">17:5<"] = "pz_floor_nature_untitled",
		[">5:7<"] = "pz_floor_nature_untitled",
		[">9:0<"] = "pz_floor_nature_untitled",
		[">12:1<"] = "pz_floor_nature_untitled",
		[">5:6<"] = "pz_floor_nature_untitled",
		[">13:7<"] = "pz_floor_nature_untitled",
		[">20:8<"] = "pz_floor_nature_untitled",
		[">11:1<"] = "pz_floor_nature_untitled",
		[">15:6<"] = "pz_floor_nature_untitled",
		[">0:1<"] = "pz_floor_nature_untitled",
		[">6:7<"] = "pz_floor_nature_untitled",
		[">13:4<"] = "pz_floor_nature_untitled",
		[">9:10<"] = "pz_floor_nature_untitled",
		[">16:4<"] = "pz_floor_nature_untitled",
		[">9:11<"] = "pz_floor_nature_untitled",
		[">14:5<"] = "pz_floor_nature_untitled",
		[">7:3<"] = "pz_floor_nature_untitled",
		[">13:3<"] = "pz_floor_nature_untitled",
		[">8:1<"] = "pz_floor_nature_untitled",
		[">10:11<"] = "pz_floor_nature_untitled",
		[">20:10<"] = "pz_floor_nature_untitled",
		[">18:4<"] = "pz_floor_nature_untitled",
		[">16:0<"] = "pz_floor_nature_untitled",
		[">18:0<"] = "pz_floor_nature_untitled",
		[">10:10<"] = "pz_floor_nature_untitled",
		[">13:8<"] = "pz_floor_nature_untitled",
		[">19:1<"] = "pz_floor_nature_untitled",
		[">11:4<"] = "pz_floor_nature_untitled",
		[">20:3<"] = "pz_floor_nature_untitled",
		[">6:6<"] = "pz_floor_nature_untitled",
		[">12:2<"] = "pz_floor_nature_untitled",
		[">4:12<"] = "pz_floor_nature_untitled",
		[">12:0<"] = "pz_floor_nature_untitled",
		[">2:9<"] = "pz_floor_nature_untitled",
		[">16:11<"] = "pz_floor_nature_untitled",
		[">12:12<"] = "pz_floor_nature_untitled",
		[">14:4<"] = "pz_floor_nature_untitled",
		[">3:8<"] = "pz_floor_nature_untitled",
		[">4:5<"] = "pz_floor_nature_untitled",
		[">1:12<"] = "pz_floor_nature_untitled",
		[">11:0<"] = "pz_floor_nature_untitled",
		[">3:3<"] = "pz_floor_nature_untitled",
		[">18:3<"] = "pz_floor_nature_untitled",
		[">4:6<"] = "pz_floor_nature_untitled",
		[">18:2<"] = "pz_floor_nature_untitled",
		[">8:9<"] = "pz_floor_nature_untitled",
		[">20:4<"] = "pz_floor_nature_untitled",
		[">16:10<"] = "pz_floor_nature_untitled",
		[">17:3<"] = "pz_floor_nature_untitled",
		[">4:4<"] = "pz_floor_nature_untitled",
		[">4:7<"] = "pz_floor_nature_untitled",
		[">9:9<"] = "pz_floor_nature_untitled",
		[">2:4<"] = "pz_floor_nature_untitled",
		[">20:2<"] = "pz_floor_nature_untitled",
		[">10:12<"] = "pz_floor_nature_untitled",
		[">20:1<"] = "pz_floor_nature_untitled",
		[">8:12<"] = "pz_floor_nature_untitled",
		[">12:11<"] = "pz_floor_nature_untitled",
		[">19:2<"] = "pz_floor_nature_untitled",
		[">0:11<"] = "pz_floor_nature_untitled",
		[">3:4<"] = "pz_floor_nature_untitled",
		[">5:9<"] = "pz_floor_nature_untitled",
		[">7:5<"] = "pz_floor_nature_untitled",
		[">17:2<"] = "pz_floor_nature_untitled",
		[">4:10<"] = "pz_floor_nature_untitled",
		[">10:8<"] = "pz_floor_nature_untitled",
		[">12:7<"] = "pz_floor_nature_untitled",
		[">1:11<"] = "pz_floor_nature_untitled",
		[">3:0<"] = "pz_floor_nature_untitled",
		[">6:4<"] = "pz_floor_nature_untitled",
		[">12:4<"] = "pz_floor_nature_untitled",
		[">16:6<"] = "pz_floor_nature_untitled",
		[">1:9<"] = "pz_floor_nature_untitled",
		[">9:8<"] = "pz_floor_nature_untitled",
		[">1:10<"] = "pz_floor_nature_untitled",
		[">16:2<"] = "pz_floor_nature_untitled",
		[">20:9<"] = "pz_floor_nature_untitled",
		[">19:11<"] = "pz_floor_nature_untitled",
		[">16:5<"] = "pz_floor_nature_untitled",
		[">14:8<"] = "pz_floor_nature_untitled",
		[">9:4<"] = "pz_floor_nature_untitled",
		[">9:5<"] = "pz_floor_nature_untitled",
		[">15:9<"] = "pz_floor_nature_untitled",
		[">15:4<"] = "pz_floor_nature_untitled",
		[">9:3<"] = "pz_floor_nature_untitled",
		[">3:12<"] = "pz_floor_nature_untitled",
		[">16:12<"] = "pz_floor_nature_untitled",
		[">11:2<"] = "pz_floor_nature_untitled",
		[">10:1<"] = "pz_floor_nature_untitled",
		[">2:8<"] = "pz_floor_nature_untitled",
		[">10:0<"] = "pz_floor_nature_untitled",
		[">16:3<"] = "pz_floor_nature_untitled",
		[">3:10<"] = "pz_floor_nature_untitled",
		[">17:0<"] = "pz_floor_nature_untitled",
		[">5:5<"] = "pz_floor_nature_untitled",
		[">17:4<"] = "pz_floor_nature_untitled",
		[">18:1<"] = "pz_floor_nature_untitled",
		[">14:6<"] = "pz_floor_nature_untitled",
		[">19:10<"] = "pz_floor_nature_untitled",
		[">17:7<"] = "pz_floor_nature_untitled",
		[">3:2<"] = "pz_floor_nature_untitled",
		[">2:2<"] = "pz_floor_nature_untitled",
		[">18:9<"] = "pz_floor_nature_untitled",
		[">11:3<"] = "pz_floor_nature_untitled",
		[">10:2<"] = "pz_floor_nature_untitled",
		[">2:11<"] = "pz_floor_nature_untitled",
		[">11:7<"] = "pz_floor_nature_untitled",
		[">5:3<"] = "pz_floor_nature_untitled",
		[">18:12<"] = "pz_floor_nature_untitled",
		[">18:10<"] = "pz_floor_nature_untitled",
		[">8:8<"] = "pz_floor_nature_untitled",
		[">3:1<"] = "pz_floor_nature_untitled",
		[">16:8<"] = "pz_floor_nature_untitled",
		[">15:7<"] = "pz_floor_nature_untitled",
		[">20:11<"] = "pz_floor_nature_untitled",
		[">11:9<"] = "pz_floor_nature_untitled",
		[">18:8<"] = "pz_floor_nature_untitled",
		[">3:9<"] = "pz_floor_nature_untitled",
		[">1:2<"] = "pz_floor_nature_untitled",
		[">12:10<"] = "pz_floor_nature_untitled",
		[">12:6<"] = "pz_floor_nature_untitled",
		[">7:9<"] = "pz_floor_nature_untitled",
		[">7:6<"] = "pz_floor_nature_untitled",
		[">3:5<"] = "pz_floor_nature_untitled",
		[">4:3<"] = "pz_floor_nature_untitled",
		[">12:5<"] = "pz_floor_nature_untitled",
		[">1:8<"] = "pz_floor_nature_untitled",
		[">12:9<"] = "pz_floor_nature_untitled",
		[">19:12<"] = "pz_floor_nature_untitled"
	             },
	["walls"] = {
		[">17:12<"] = "pz_wall_nature_bush",
		[">12:1<"] = "pz_wall_nature_bush",
		[">6:4<"] = "pz_wall_nature_bush",
		[">4:1<"] = "pz_wall_nature_bush",
		[">0:1<"] = "pz_wall_nature_bush",
		[">4:2<"] = "pz_wall_nature_bush",
		[">12:12<"] = "pz_wall_nature_bush",
		[">20:1<"] = "pz_wall_nature_bush",
		[">8:1<"] = "pz_wall_nature_bush",
		[">4:0<"] = "pz_wall_nature_bush",
		[">18:4<"] = "pz_wall_nature_bush",
		[">16:0<"] = "pz_wall_nature_bush",
		[">18:0<"] = "pz_wall_nature_bush",
		[">1:0<"] = "pz_wall_nature_bush",
		[">20:3<"] = "pz_wall_nature_bush",
		[">8:11<"] = "pz_wall_nature_bush",
		[">12:0<"] = "pz_wall_nature_bush",
		[">16:11<"] = "pz_wall_nature_bush",
		[">8:6<"] = "pz_wall_nature_bush",
		[">13:9<"] = "pz_wall_nature_bush",
		[">1:12<"] = "pz_wall_nature_bush",
		[">11:0<"] = "pz_wall_nature_bush",
		[">19:8<"] = "pz_wall_nature_bush",
		[">18:12<"] = "pz_wall_nature_bush",
		[">16:10<"] = "pz_wall_nature_bush",
		[">5:3<"] = "pz_wall_nature_bush",
		[">13:3<"] = "pz_wall_nature_bush",
		[">0:10<"] = "pz_wall_nature_bush",
		[">8:0<"] = "pz_wall_nature_bush",
		[">0:2<"] = "pz_wall_nature_bush",
		[">0:11<"] = "pz_wall_nature_bush",
		[">4:11<"] = "pz_wall_nature_bush",
		[">4:10<"] = "pz_wall_nature_bush",
		[">10:8<"] = "pz_wall_nature_bush",
		[">20:12<"] = "pz_wall_nature_bush",
		[">3:5<"] = "pz_wall_nature_bush",
		[">3:7<"] = "pz_wall_nature_bush",
		[">3:0<"] = "pz_wall_nature_bush",
		[">0:8<"] = "pz_wall_nature_bush",
		[">16:6<"] = "pz_wall_nature_bush",
		[">2:12<"] = "pz_wall_nature_bush",
		[">10:4<"] = "pz_wall_nature_bush",
		[">16:2<"] = "pz_wall_nature_bush",
		[">20:9<"] = "pz_wall_nature_bush",
		[">16:12<"] = "pz_wall_nature_bush",
		[">8:2<"] = "pz_wall_nature_bush",
		[">14:8<"] = "pz_wall_nature_bush",
		[">9:12<"] = "pz_wall_nature_bush",
		[">9:5<"] = "pz_wall_nature_bush",
		[">15:9<"] = "pz_wall_nature_bush",
		[">17:5<"] = "pz_wall_nature_bush",
		[">9:7<"] = "pz_wall_nature_bush",
		[">3:12<"] = "pz_wall_nature_bush",
		[">15:3<"] = "pz_wall_nature_bush",
		[">0:3<"] = "pz_wall_nature_bush",
		[">7:9<"] = "pz_wall_nature_bush",
		[">2:8<"] = "pz_wall_nature_bush",
		[">10:12<"] = "pz_wall_nature_bush",
		[">16:1<"] = "pz_wall_nature_bush",
		[">6:8<"] = "pz_wall_nature_bush",
		[">0:0<"] = "pz_wall_nature_bush",
		[">20:10<"] = "pz_wall_nature_bush",
		[">12:6<"] = "pz_wall_nature_bush",
		[">8:10<"] = "pz_wall_nature_bush",
		[">0:12<"] = "pz_wall_nature_bush",
		[">12:11<"] = "pz_wall_nature_bush",
		[">17:7<"] = "pz_wall_nature_bush",
		[">4:12<"] = "pz_wall_nature_bush",
		[">17:0<"] = "pz_wall_nature_bush",
		[">2:4<"] = "pz_wall_nature_bush",
		[">20:4<"] = "pz_wall_nature_bush",
		[">20:8<"] = "pz_wall_nature_bush",
		[">4:6<"] = "pz_wall_nature_bush",
		[">0:9<"] = "pz_wall_nature_bush",
		[">19:0<"] = "pz_wall_nature_bush",
		[">14:4<"] = "pz_wall_nature_bush",
		[">7:3<"] = "pz_wall_nature_bush",
		[">20:11<"] = "pz_wall_nature_bush",
		[">11:7<"] = "pz_wall_nature_bush",
		[">20:2<"] = "pz_wall_nature_bush",
		[">20:0<"] = "pz_wall_nature_bush",
		[">5:9<"] = "pz_wall_nature_bush",
		[">8:12<"] = "pz_wall_nature_bush",
		[">18:8<"] = "pz_wall_nature_bush",
		[">1:4<"] = "pz_wall_nature_bush",
		[">9:0<"] = "pz_wall_nature_bush",
		[">12:10<"] = "pz_wall_nature_bush",
		[">0:4<"] = "pz_wall_nature_bush",
		[">11:12<"] = "pz_wall_nature_bush",
		[">19:4<"] = "pz_wall_nature_bush",
		[">11:5<"] = "pz_wall_nature_bush",
		[">2:0<"] = "pz_wall_nature_bush",
		[">12:2<"] = "pz_wall_nature_bush",
		[">1:8<"] = "pz_wall_nature_bush",
		[">10:0<"] = "pz_wall_nature_bush",
		[">19:12<"] = "pz_wall_nature_bush"
	            },
	["title"] = "\73\116\39\115\32\110\111\116\32\101\97\115\121\32\98\101\105\110\103\32\103\114\101\101\110\46",
	["tools"] = {
		["plate2"] = 20,
		["plate1"] = 20,
		["trash"] = 5,
		["barrier"] = 1
	            },
	["reqballs"] = 18,
	["missionnum"] = 1,
	["mission"] = "Normal",
	["objects"] = {
		[14] = {
			["y"] = 3,
			["x"] = 19,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[2] = {
			["y"] = 11,
			["x"] = 9,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[12] = {
			["y"] = 11,
			["x"] = 19,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[11] = {
			["y"] = 11,
			["x"] = 17,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[10] = {
			["y"] = 11,
			["x"] = 3,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[9] = {
			["y"] = 11,
			["x"] = 1,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[8] = {
			["y"] = 9,
			["x"] = 1,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[7] = {
			["y"] = 3,
			["x"] = 1,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[1] = {
			["y"] = 11,
			["x"] = 11,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[6] = {
			["y"] = 1,
			["x"] = 1,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[5] = {
			["y"] = 1,
			["x"] = 3,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[4] = {
			["y"] = 1,
			["x"] = 9,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[3] = {
			["y"] = 1,
			["x"] = 11,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[18] = {
			["y"] = 6,
			["x"] = 6,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[17] = {
			["y"] = 6,
			["x"] = 14,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[16] = {
			["y"] = 1,
			["x"] = 17,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[15] = {
			["y"] = 1,
			["x"] = 19,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[13] = {
			["y"] = 9,
			["x"] = 19,
			["kind"] = "ball",
			["dir"] = "D"
		       }
	              }
       }


ret2 = {
	["strip"] = {
		["wall"] = {
			["cstrip"] = "nature",
			["tile"] = "pz_wall_nature_bush"
		           },
		["floor"] = {
			["cstrip"] = "nature",
			["tile"] = "pz_floor_nature_untitled"
		            },
		["exits"] = {
			["tile"] = "a_exit"
		            }
	            },
	["tab"] = "settings"
       }




return ret1, ret2


