--[[
	BallPlay Cupid
	Puzzle 22
	
	
	
	(c) Jeroen P. Broks, 2016, All rights reserved
	
		This program is free software: you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.
		
		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
		You should have received a copy of the GNU General Public License
		along with this program.  If not, see <http://www.gnu.org/licenses/>.
		
	Exceptions to the standard GNU license are available with Jeroen's written permission given prior 
	to the project the exceptions are needed for.
Version: 16.04.26
]]

  -- This file has been generated by BallPlay Cupid.
  -- and may only be used in combination with that game
  -- and in unmodified form. 
  -- unless stated otherwise in the game license.


local ret1, ret2



ret1 = {
	["format"] = {
		[2] = 15,
		[1] = 25
	             },
	["partime"] = 0,
	["floors"] = {
		[">5:7<"] = "pz_floor_desert_des_sand",
		[">5:6<"] = "pz_floor_desert_des_sand",
		[">13:7<"] = "pz_floor_desert_des_sand",
		[">5:9<"] = "pz_floor_desert_des_sand",
		[">6:12<"] = "pz_floor_desert_des_sand",
		[">6:7<"] = "pz_floor_desert_des_sand",
		[">3:11<"] = "pz_floor_desert_des_sand",
		[">5:12<"] = "pz_floor_desert_des_sand",
		[">9:11<"] = "pz_floor_desert_des_sand",
		[">14:5<"] = "pz_floor_desert_des_sand",
		[">10:5<"] = "pz_floor_desert_des_sand",
		[">10:11<"] = "pz_floor_desert_des_sand",
		[">3:5<"] = "pz_floor_desert_des_sand",
		[">5:8<"] = "pz_floor_desert_des_sand",
		[">10:10<"] = "pz_floor_desert_des_sand",
		[">6:6<"] = "pz_floor_desert_des_sand",
		[">7:11<"] = "pz_floor_desert_des_sand",
		[">4:12<"] = "pz_floor_desert_des_sand",
		[">3:7<"] = "pz_floor_desert_des_sand",
		[">16:11<"] = "pz_floor_desert_des_sand",
		[">10:9<"] = "pz_floor_desert_des_sand",
		[">8:6<"] = "pz_floor_desert_des_sand",
		[">3:8<"] = "pz_floor_desert_des_sand",
		[">13:9<"] = "pz_floor_desert_des_sand",
		[">12:9<"] = "pz_floor_desert_des_sand",
		[">13:6<"] = "pz_floor_desert_des_sand",
		[">11:6<"] = "pz_floor_desert_des_sand",
		[">6:10<"] = "pz_floor_desert_des_sand",
		[">16:7<"] = "pz_floor_desert_des_sand",
		[">7:9<"] = "pz_floor_desert_des_sand",
		[">16:10<"] = "pz_floor_desert_des_sand",
		[">5:10<"] = "pz_floor_desert_des_sand",
		[">13:12<"] = "pz_floor_desert_des_sand",
		[">13:5<"] = "pz_floor_desert_des_sand",
		[">9:9<"] = "pz_floor_desert_des_sand",
		[">14:11<"] = "pz_floor_desert_des_sand",
		[">4:5<"] = "pz_floor_desert_des_sand",
		[">10:12<"] = "pz_floor_desert_des_sand",
		[">3:6<"] = "pz_floor_desert_des_sand",
		[">15:12<"] = "pz_floor_desert_des_sand",
		[">12:10<"] = "pz_floor_desert_des_sand",
		[">11:5<"] = "pz_floor_desert_des_sand",
		[">15:6<"] = "pz_floor_desert_des_sand",
		[">10:8<"] = "pz_floor_desert_des_sand",
		[">7:7<"] = "pz_floor_desert_des_sand",
		[">7:5<"] = "pz_floor_desert_des_sand",
		[">4:11<"] = "pz_floor_desert_des_sand",
		[">4:10<"] = "pz_floor_desert_des_sand",
		[">14:10<"] = "pz_floor_desert_des_sand",
		[">10:7<"] = "pz_floor_desert_des_sand",
		[">6:8<"] = "pz_floor_desert_des_sand",
		[">7:10<"] = "pz_floor_desert_des_sand",
		[">15:10<"] = "pz_floor_desert_des_sand",
		[">11:8<"] = "pz_floor_desert_des_sand",
		[">9:10<"] = "pz_floor_desert_des_sand",
		[">14:9<"] = "pz_floor_desert_des_sand",
		[">12:5<"] = "pz_floor_desert_des_sand",
		[">7:8<"] = "pz_floor_desert_des_sand",
		[">15:9<"] = "pz_floor_desert_des_sand",
		[">13:8<"] = "pz_floor_desert_des_sand",
		[">16:12<"] = "pz_floor_desert_des_sand",
		[">16:5<"] = "pz_floor_desert_des_sand",
		[">5:11<"] = "pz_floor_desert_des_sand",
		[">9:12<"] = "pz_floor_desert_des_sand",
		[">9:5<"] = "pz_floor_desert_des_sand",
		[">15:8<"] = "pz_floor_desert_des_sand",
		[">11:10<"] = "pz_floor_desert_des_sand",
		[">7:6<"] = "pz_floor_desert_des_sand",
		[">3:12<"] = "pz_floor_desert_des_sand",
		[">12:12<"] = "pz_floor_desert_des_sand",
		[">6:9<"] = "pz_floor_desert_des_sand",
		[">3:10<"] = "pz_floor_desert_des_sand",
		[">16:6<"] = "pz_floor_desert_des_sand",
		[">13:10<"] = "pz_floor_desert_des_sand",
		[">9:6<"] = "pz_floor_desert_des_sand",
		[">4:8<"] = "pz_floor_desert_des_sand",
		[">11:11<"] = "pz_floor_desert_des_sand",
		[">12:7<"] = "pz_floor_desert_des_sand",
		[">4:6<"] = "pz_floor_desert_des_sand",
		[">10:6<"] = "pz_floor_desert_des_sand",
		[">14:6<"] = "pz_floor_desert_des_sand",
		[">12:11<"] = "pz_floor_desert_des_sand",
		[">8:12<"] = "pz_floor_desert_des_sand",
		[">12:6<"] = "pz_floor_desert_des_sand",
		[">13:11<"] = "pz_floor_desert_des_sand",
		[">8:9<"] = "pz_floor_desert_des_sand",
		[">4:7<"] = "pz_floor_desert_des_sand",
		[">14:12<"] = "pz_floor_desert_des_sand",
		[">6:5<"] = "pz_floor_desert_des_sand",
		[">11:7<"] = "pz_floor_desert_des_sand",
		[">5:5<"] = "pz_floor_desert_des_sand",
		[">9:8<"] = "pz_floor_desert_des_sand",
		[">12:8<"] = "pz_floor_desert_des_sand",
		[">8:8<"] = "pz_floor_desert_des_sand",
		[">9:7<"] = "pz_floor_desert_des_sand",
		[">8:5<"] = "pz_floor_desert_des_sand",
		[">15:7<"] = "pz_floor_desert_des_sand",
		[">15:5<"] = "pz_floor_desert_des_sand",
		[">11:9<"] = "pz_floor_desert_des_sand",
		[">8:10<"] = "pz_floor_desert_des_sand",
		[">8:11<"] = "pz_floor_desert_des_sand",
		[">6:11<"] = "pz_floor_desert_des_sand",
		[">15:11<"] = "pz_floor_desert_des_sand",
		[">4:9<"] = "pz_floor_desert_des_sand",
		[">11:12<"] = "pz_floor_desert_des_sand",
		[">8:7<"] = "pz_floor_desert_des_sand",
		[">16:8<"] = "pz_floor_desert_des_sand",
		[">7:12<"] = "pz_floor_desert_des_sand",
		[">16:9<"] = "pz_floor_desert_des_sand",
		[">3:9<"] = "pz_floor_desert_des_sand",
		[">14:8<"] = "pz_floor_desert_des_sand",
		[">14:7<"] = "pz_floor_desert_des_sand"
	             },
	["ghostwomen"] = {},
	["obstacles"] = {
		[">14:10<"] = "womanhome",
		[">11:8<"] = "zplate2",
		[">8:10<"] = "zplate2",
		[">8:9<"] = "zplate1",
		[">11:11<"] = "zplate1",
		[">9:6<"] = "zplate2",
		[">10:8<"] = "zplate2",
		[">11:9<"] = "zplate1",
		[">9:11<"] = "zplate2",
		[">11:10<"] = "zplate2",
		[">10:6<"] = "zplate1"
	                },
	["mission"] = "Walkthrough",
	["walls"] = {
		[">7:7<"] = "pz_wall_desert_des_pyramid",
		[">12:5<"] = "pz_wall_desert_des_pyramid",
		[">7:8<"] = "pz_wall_desert_des_pyramid",
		[">3:11<"] = "pz_wall_desert_des_pyramid",
		[">5:12<"] = "pz_wall_desert_des_pyramid",
		[">13:5<"] = "pz_wall_desert_des_pyramid",
		[">14:5<"] = "pz_wall_desert_des_pyramid",
		[">13:12<"] = "pz_wall_desert_des_pyramid",
		[">10:5<"] = "pz_wall_desert_des_pyramid",
		[">16:5<"] = "pz_wall_desert_des_pyramid",
		[">3:5<"] = "pz_wall_desert_des_pyramid",
		[">15:12<"] = "pz_wall_desert_des_pyramid",
		[">12:8<"] = "pz_wall_desert_des_pyramid",
		[">9:5<"] = "pz_wall_desert_des_pyramid",
		[">16:6<"] = "pz_wall_desert_des_pyramid",
		[">12:12<"] = "pz_wall_desert_des_pyramid",
		[">16:8<"] = "pz_wall_desert_des_pyramid",
		[">3:10<"] = "pz_wall_desert_des_pyramid",
		[">8:7<"] = "pz_wall_desert_des_pyramid",
		[">5:5<"] = "pz_wall_desert_des_pyramid",
		[">4:12<"] = "pz_wall_desert_des_pyramid",
		[">3:7<"] = "pz_wall_desert_des_pyramid",
		[">3:12<"] = "pz_wall_desert_des_pyramid",
		[">12:11<"] = "pz_wall_desert_des_pyramid",
		[">8:12<"] = "pz_wall_desert_des_pyramid",
		[">7:11<"] = "pz_wall_desert_des_pyramid",
		[">3:8<"] = "pz_wall_desert_des_pyramid",
		[">4:5<"] = "pz_wall_desert_des_pyramid",
		[">12:9<"] = "pz_wall_desert_des_pyramid",
		[">7:10<"] = "pz_wall_desert_des_pyramid",
		[">6:5<"] = "pz_wall_desert_des_pyramid",
		[">11:7<"] = "pz_wall_desert_des_pyramid",
		[">16:7<"] = "pz_wall_desert_des_pyramid",
		[">7:9<"] = "pz_wall_desert_des_pyramid",
		[">12:10<"] = "pz_wall_desert_des_pyramid",
		[">8:8<"] = "pz_wall_desert_des_pyramid",
		[">16:10<"] = "pz_wall_desert_des_pyramid",
		[">8:5<"] = "pz_wall_desert_des_pyramid",
		[">14:12<"] = "pz_wall_desert_des_pyramid",
		[">15:5<"] = "pz_wall_desert_des_pyramid",
		[">3:9<"] = "pz_wall_desert_des_pyramid",
		[">16:11<"] = "pz_wall_desert_des_pyramid",
		[">16:12<"] = "pz_wall_desert_des_pyramid",
		[">10:12<"] = "pz_wall_desert_des_pyramid",
		[">3:6<"] = "pz_wall_desert_des_pyramid",
		[">8:11<"] = "pz_wall_desert_des_pyramid",
		[">11:12<"] = "pz_wall_desert_des_pyramid",
		[">9:12<"] = "pz_wall_desert_des_pyramid",
		[">11:5<"] = "pz_wall_desert_des_pyramid",
		[">7:12<"] = "pz_wall_desert_des_pyramid",
		[">16:9<"] = "pz_wall_desert_des_pyramid",
		[">7:5<"] = "pz_wall_desert_des_pyramid",
		[">6:12<"] = "pz_wall_desert_des_pyramid",
		[">12:7<"] = "pz_wall_desert_des_pyramid"
	            },
	["title"] = "There is no place like home",
	["falling"] = {},
	["reqballs"] = 9,
	["missionnum"] = 7,
	["tools"] = {
		["plate2"] = 7,
		["plate1"] = 7,
		["trash"] = 0,
		["barrier"] = 0
	            },
	["objects"] = {
		[14] = {
			["y"] = 11,
			["x"] = 6,
			["kind"] = "ghostgreen",
			["dir"] = "R"
		       },
		[2] = {
			["y"] = 8,
			["x"] = 13,
			["kind"] = "ball",
			["dir"] = "R"
		      },
		[12] = {
			["y"] = 11,
			["x"] = 5,
			["kind"] = "ghostamber",
			["dir"] = "R"
		       },
		[11] = {
			["y"] = 11,
			["x"] = 14,
			["kind"] = "ball",
			["dir"] = "R"
		       },
		[10] = {
			["y"] = 9,
			["x"] = 13,
			["kind"] = "ball",
			["dir"] = "D"
		       },
		[9] = {
			["y"] = 10,
			["x"] = 13,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[23] = {
			["y"] = 8,
			["x"] = 6,
			["kind"] = "ghostblue",
			["dir"] = "R"
		       },
		[8] = {
			["y"] = 11,
			["x"] = 13,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[19] = {
			["y"] = 9,
			["x"] = 5,
			["kind"] = "ghostred",
			["dir"] = "R"
		       },
		[7] = {
			["y"] = 11,
			["x"] = 15,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[1] = {
			["y"] = 10,
			["x"] = 9,
			["kind"] = "woman",
			["dir"] = "D"
		      },
		[6] = {
			["y"] = 10,
			["x"] = 15,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[5] = {
			["y"] = 9,
			["x"] = 15,
			["kind"] = "ball",
			["dir"] = "D"
		      },
		[4] = {
			["y"] = 8,
			["x"] = 15,
			["kind"] = "ball",
			["dir"] = "R"
		      },
		[21] = {
			["y"] = 9,
			["x"] = 6,
			["kind"] = "ghostamber",
			["dir"] = "R"
		       },
		[22] = {
			["y"] = 8,
			["x"] = 5,
			["kind"] = "ghostamber",
			["dir"] = "R"
		       },
		[18] = {
			["y"] = 9,
			["x"] = 4,
			["kind"] = "ghostblue",
			["dir"] = "R"
		       },
		[20] = {
			["y"] = 8,
			["x"] = 4,
			["kind"] = "ghostred",
			["dir"] = "R"
		       },
		[3] = {
			["y"] = 8,
			["x"] = 14,
			["kind"] = "ball",
			["dir"] = "R"
		      },
		[17] = {
			["y"] = 10,
			["x"] = 4,
			["kind"] = "ghostamber",
			["dir"] = "R"
		       },
		[16] = {
			["y"] = 10,
			["x"] = 5,
			["kind"] = "ghostgreen",
			["dir"] = "R"
		       },
		[15] = {
			["y"] = 10,
			["x"] = 6,
			["kind"] = "ghostred",
			["dir"] = "R"
		       },
		[13] = {
			["y"] = 11,
			["x"] = 4,
			["kind"] = "ghostblue",
			["dir"] = "R"
		       }
	              }
       }


ret2 = {
	["tab"] = "settings",
	["strip"] = {
		["floor"] = {
			["cstrip"] = "desert",
			["tile"] = "pz_floor_desert_des_sand"
		            },
		["plates"] = {
			["tile"] = "zplate2"
		             },
		["wall"] = {
			["cstrip"] = "desert",
			["tile"] = "pz_wall_desert_des_pyramid"
		           },
		["exits"] = {
			["tile"] = "womanhome"
		            }
	            },
	["odir"] = 4
       }




return ret1, ret2


