--[[
	BallPlay Cupid
	Puzzle #23
	
	
	
	(c) Jeroen P. Broks, 2016, All rights reserved
	
		This program is free software: you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.
		
		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
		You should have received a copy of the GNU General Public License
		along with this program.  If not, see <http://www.gnu.org/licenses/>.
		
	Exceptions to the standard GNU license are available with Jeroen's written permission given prior 
	to the project the exceptions are needed for.
Version: 16.05.01
]]

  -- This file has been generated by BallPlay Cupid.
  -- and may only be used in combination with that game
  -- and in unmodified form. 
  -- unless stated otherwise in the game license.


local ret1, ret2



ret1 = {
	["format"] = {
		[1] = 25,
		[2] = 15
	             },
	["partime"] = 0,
	["mission"] = "Normal",
	["missionnum"] = 1,
	["tools"] = {
		["plate2"] = 100,
		["plate1"] = 100,
		["trash"] = 0,
		["barrier"] = 0
	            },
	["floors"] = {
		[">8:10<"] = "pz_floor_nature_untitled",
		[">12:13<"] = "pz_floor_nature_untitled",
		[">9:2<"] = "pz_floor_nature_untitled",
		[">14:4<"] = "pz_floor_nature_untitled",
		[">12:12<"] = "pz_floor_nature_untitled",
		[">13:5<"] = "pz_floor_nature_untitled",
		[">16:1<"] = "pz_floor_nature_untitled",
		[">10:5<"] = "pz_floor_nature_untitled",
		[">17:14<"] = "pz_floor_nature_untitled",
		[">8:4<"] = "pz_floor_nature_untitled",
		[">18:11<"] = "pz_floor_nature_untitled",
		[">12:14<"] = "pz_floor_nature_untitled",
		[">7:11<"] = "pz_floor_nature_untitled",
		[">7:10<"] = "pz_floor_nature_untitled",
		[">10:9<"] = "pz_floor_nature_untitled",
		[">8:6<"] = "pz_floor_nature_untitled",
		[">13:9<"] = "pz_floor_nature_untitled",
		[">13:6<"] = "pz_floor_nature_untitled",
		[">16:7<"] = "pz_floor_nature_untitled",
		[">17:9<"] = "pz_floor_nature_untitled",
		[">20:13<"] = "pz_floor_nature_untitled",
		[">11:11<"] = "pz_floor_nature_untitled",
		[">10:3<"] = "pz_floor_nature_untitled",
		[">6:13<"] = "pz_floor_nature_untitled",
		[">7:7<"] = "pz_floor_nature_untitled",
		[">9:3<"] = "pz_floor_nature_untitled",
		[">16:3<"] = "pz_floor_nature_untitled",
		[">12:5<"] = "pz_floor_nature_untitled",
		[">10:4<"] = "pz_floor_nature_untitled",
		[">8:2<"] = "pz_floor_nature_untitled",
		[">9:1<"] = "pz_floor_nature_untitled",
		[">17:8<"] = "pz_floor_nature_untitled",
		[">15:8<"] = "pz_floor_nature_untitled",
		[">9:7<"] = "pz_floor_nature_untitled",
		[">9:14<"] = "pz_floor_nature_untitled",
		[">17:11<"] = "pz_floor_nature_untitled",
		[">12:3<"] = "pz_floor_nature_untitled",
		[">18:14<"] = "pz_floor_nature_untitled",
		[">7:4<"] = "pz_floor_nature_untitled",
		[">13:2<"] = "pz_floor_nature_untitled",
		[">11:10<"] = "pz_floor_nature_untitled",
		[">12:6<"] = "pz_floor_nature_untitled",
		[">8:3<"] = "pz_floor_nature_untitled",
		[">6:5<"] = "pz_floor_nature_untitled",
		[">11:13<"] = "pz_floor_nature_untitled",
		[">8:5<"] = "pz_floor_nature_untitled",
		[">15:5<"] = "pz_floor_nature_untitled",
		[">11:8<"] = "pz_floor_nature_untitled",
		[">17:13<"] = "pz_floor_nature_untitled",
		[">17:6<"] = "pz_floor_nature_untitled",
		[">15:11<"] = "pz_floor_nature_untitled",
		[">11:12<"] = "pz_floor_nature_untitled",
		[">11:5<"] = "pz_floor_nature_untitled",
		[">16:9<"] = "pz_floor_nature_untitled",
		[">15:1<"] = "pz_floor_nature_untitled",
		[">17:12<"] = "pz_floor_nature_untitled",
		[">12:1<"] = "pz_floor_nature_untitled",
		[">15:10<"] = "pz_floor_nature_untitled",
		[">13:7<"] = "pz_floor_nature_untitled",
		[">11:1<"] = "pz_floor_nature_untitled",
		[">15:6<"] = "pz_floor_nature_untitled",
		[">6:12<"] = "pz_floor_nature_untitled",
		[">15:12<"] = "pz_floor_nature_untitled",
		[">13:4<"] = "pz_floor_nature_untitled",
		[">9:11<"] = "pz_floor_nature_untitled",
		[">14:5<"] = "pz_floor_nature_untitled",
		[">8:1<"] = "pz_floor_nature_untitled",
		[">10:11<"] = "pz_floor_nature_untitled",
		[">15:13<"] = "pz_floor_nature_untitled",
		[">19:12<"] = "pz_floor_nature_untitled",
		[">10:8<"] = "pz_floor_nature_untitled",
		[">10:10<"] = "pz_floor_nature_untitled",
		[">13:8<"] = "pz_floor_nature_untitled",
		[">7:8<"] = "pz_floor_nature_untitled",
		[">11:6<"] = "pz_floor_nature_untitled",
		[">9:12<"] = "pz_floor_nature_untitled",
		[">6:6<"] = "pz_floor_nature_untitled",
		[">15:2<"] = "pz_floor_nature_untitled",
		[">8:11<"] = "pz_floor_nature_untitled",
		[">18:10<"] = "pz_floor_nature_untitled",
		[">7:9<"] = "pz_floor_nature_untitled",
		[">16:11<"] = "pz_floor_nature_untitled",
		[">9:13<"] = "pz_floor_nature_untitled",
		[">12:8<"] = "pz_floor_nature_untitled",
		[">13:11<"] = "pz_floor_nature_untitled",
		[">20:11<"] = "pz_floor_nature_untitled",
		[">12:9<"] = "pz_floor_nature_untitled",
		[">20:12<"] = "pz_floor_nature_untitled",
		[">10:13<"] = "pz_floor_nature_untitled",
		[">6:10<"] = "pz_floor_nature_untitled",
		[">8:14<"] = "pz_floor_nature_untitled",
		[">17:5<"] = "pz_floor_nature_untitled",
		[">16:4<"] = "pz_floor_nature_untitled",
		[">20:14<"] = "pz_floor_nature_untitled",
		[">16:10<"] = "pz_floor_nature_untitled",
		[">17:3<"] = "pz_floor_nature_untitled",
		[">17:4<"] = "pz_floor_nature_untitled",
		[">7:13<"] = "pz_floor_nature_untitled",
		[">9:9<"] = "pz_floor_nature_untitled",
		[">14:11<"] = "pz_floor_nature_untitled",
		[">18:12<"] = "pz_floor_nature_untitled",
		[">10:12<"] = "pz_floor_nature_untitled",
		[">14:3<"] = "pz_floor_nature_untitled",
		[">15:3<"] = "pz_floor_nature_untitled",
		[">8:7<"] = "pz_floor_nature_untitled",
		[">17:2<"] = "pz_floor_nature_untitled",
		[">6:8<"] = "pz_floor_nature_untitled",
		[">6:11<"] = "pz_floor_nature_untitled",
		[">14:1<"] = "pz_floor_nature_untitled",
		[">7:5<"] = "pz_floor_nature_untitled",
		[">15:14<"] = "pz_floor_nature_untitled",
		[">16:13<"] = "pz_floor_nature_untitled",
		[">14:10<"] = "pz_floor_nature_untitled",
		[">13:1<"] = "pz_floor_nature_untitled",
		[">12:2<"] = "pz_floor_nature_untitled",
		[">12:4<"] = "pz_floor_nature_untitled",
		[">11:3<"] = "pz_floor_nature_untitled",
		[">10:14<"] = "pz_floor_nature_untitled",
		[">18:9<"] = "pz_floor_nature_untitled",
		[">14:7<"] = "pz_floor_nature_untitled",
		[">11:2<"] = "pz_floor_nature_untitled",
		[">17:7<"] = "pz_floor_nature_untitled",
		[">16:2<"] = "pz_floor_nature_untitled",
		[">11:14<"] = "pz_floor_nature_untitled",
		[">16:12<"] = "pz_floor_nature_untitled",
		[">16:5<"] = "pz_floor_nature_untitled",
		[">14:8<"] = "pz_floor_nature_untitled",
		[">13:12<"] = "pz_floor_nature_untitled",
		[">9:5<"] = "pz_floor_nature_untitled",
		[">14:13<"] = "pz_floor_nature_untitled",
		[">15:4<"] = "pz_floor_nature_untitled",
		[">16:14<"] = "pz_floor_nature_untitled",
		[">17:10<"] = "pz_floor_nature_untitled",
		[">9:4<"] = "pz_floor_nature_untitled",
		[">16:6<"] = "pz_floor_nature_untitled",
		[">10:1<"] = "pz_floor_nature_untitled",
		[">9:8<"] = "pz_floor_nature_untitled",
		[">13:10<"] = "pz_floor_nature_untitled",
		[">9:6<"] = "pz_floor_nature_untitled",
		[">6:9<"] = "pz_floor_nature_untitled",
		[">7:6<"] = "pz_floor_nature_untitled",
		[">12:7<"] = "pz_floor_nature_untitled",
		[">9:10<"] = "pz_floor_nature_untitled",
		[">10:6<"] = "pz_floor_nature_untitled",
		[">14:6<"] = "pz_floor_nature_untitled",
		[">12:11<"] = "pz_floor_nature_untitled",
		[">8:12<"] = "pz_floor_nature_untitled",
		[">14:14<"] = "pz_floor_nature_untitled",
		[">18:7<"] = "pz_floor_nature_untitled",
		[">8:9<"] = "pz_floor_nature_untitled",
		[">14:12<"] = "pz_floor_nature_untitled",
		[">6:4<"] = "pz_floor_nature_untitled",
		[">16:8<"] = "pz_floor_nature_untitled",
		[">11:7<"] = "pz_floor_nature_untitled",
		[">13:13<"] = "pz_floor_nature_untitled",
		[">11:4<"] = "pz_floor_nature_untitled",
		[">6:7<"] = "pz_floor_nature_untitled",
		[">8:8<"] = "pz_floor_nature_untitled",
		[">19:14<"] = "pz_floor_nature_untitled",
		[">10:7<"] = "pz_floor_nature_untitled",
		[">15:7<"] = "pz_floor_nature_untitled",
		[">14:9<"] = "pz_floor_nature_untitled",
		[">11:9<"] = "pz_floor_nature_untitled",
		[">18:8<"] = "pz_floor_nature_untitled",
		[">19:13<"] = "pz_floor_nature_untitled",
		[">13:3<"] = "pz_floor_nature_untitled",
		[">12:10<"] = "pz_floor_nature_untitled",
		[">10:2<"] = "pz_floor_nature_untitled",
		[">18:13<"] = "pz_floor_nature_untitled",
		[">19:11<"] = "pz_floor_nature_untitled",
		[">17:1<"] = "pz_floor_nature_untitled",
		[">7:12<"] = "pz_floor_nature_untitled",
		[">8:13<"] = "pz_floor_nature_untitled",
		[">14:2<"] = "pz_floor_nature_untitled",
		[">15:9<"] = "pz_floor_nature_untitled",
		[">13:14<"] = "pz_floor_nature_untitled"
	             },
	["walls"] = {
		[">12:1<"] = "pz_wall_nature_bush",
		[">6:4<"] = "pz_wall_nature_bush",
		[">13:7<"] = "pz_wall_nature_bush",
		[">11:1<"] = "pz_wall_nature_bush",
		[">15:6<"] = "pz_wall_nature_bush",
		[">6:12<"] = "pz_wall_nature_bush",
		[">6:7<"] = "pz_wall_nature_bush",
		[">13:4<"] = "pz_wall_nature_bush",
		[">14:4<"] = "pz_wall_nature_bush",
		[">13:5<"] = "pz_wall_nature_bush",
		[">14:5<"] = "pz_wall_nature_bush",
		[">16:1<"] = "pz_wall_nature_bush",
		[">8:1<"] = "pz_wall_nature_bush",
		[">14:3<"] = "pz_wall_nature_bush",
		[">8:4<"] = "pz_wall_nature_bush",
		[">18:11<"] = "pz_wall_nature_bush",
		[">12:14<"] = "pz_wall_nature_bush",
		[">20:11<"] = "pz_wall_nature_bush",
		[">16:11<"] = "pz_wall_nature_bush",
		[">13:11<"] = "pz_wall_nature_bush",
		[">13:9<"] = "pz_wall_nature_bush",
		[">13:6<"] = "pz_wall_nature_bush",
		[">6:11<"] = "pz_wall_nature_bush",
		[">6:10<"] = "pz_wall_nature_bush",
		[">17:5<"] = "pz_wall_nature_bush",
		[">17:3<"] = "pz_wall_nature_bush",
		[">17:4<"] = "pz_wall_nature_bush",
		[">7:13<"] = "pz_wall_nature_bush",
		[">14:11<"] = "pz_wall_nature_bush",
		[">20:13<"] = "pz_wall_nature_bush",
		[">13:3<"] = "pz_wall_nature_bush",
		[">14:1<"] = "pz_wall_nature_bush",
		[">8:13<"] = "pz_wall_nature_bush",
		[">14:10<"] = "pz_wall_nature_bush",
		[">13:8<"] = "pz_wall_nature_bush",
		[">12:4<"] = "pz_wall_nature_bush",
		[">19:11<"] = "pz_wall_nature_bush",
		[">8:2<"] = "pz_wall_nature_bush",
		[">9:1<"] = "pz_wall_nature_bush",
		[">20:14<"] = "pz_wall_nature_bush",
		[">15:4<"] = "pz_wall_nature_bush",
		[">13:14<"] = "pz_wall_nature_bush",
		[">9:14<"] = "pz_wall_nature_bush",
		[">15:3<"] = "pz_wall_nature_bush",
		[">12:3<"] = "pz_wall_nature_bush",
		[">10:1<"] = "pz_wall_nature_bush",
		[">17:2<"] = "pz_wall_nature_bush",
		[">13:10<"] = "pz_wall_nature_bush",
		[">6:9<"] = "pz_wall_nature_bush",
		[">17:14<"] = "pz_wall_nature_bush",
		[">11:3<"] = "pz_wall_nature_bush",
		[">19:14<"] = "pz_wall_nature_bush",
		[">20:12<"] = "pz_wall_nature_bush",
		[">17:11<"] = "pz_wall_nature_bush",
		[">14:6<"] = "pz_wall_nature_bush",
		[">18:10<"] = "pz_wall_nature_bush",
		[">17:7<"] = "pz_wall_nature_bush",
		[">14:14<"] = "pz_wall_nature_bush",
		[">18:7<"] = "pz_wall_nature_bush",
		[">18:9<"] = "pz_wall_nature_bush",
		[">8:3<"] = "pz_wall_nature_bush",
		[">15:14<"] = "pz_wall_nature_bush",
		[">6:5<"] = "pz_wall_nature_bush",
		[">6:8<"] = "pz_wall_nature_bush",
		[">10:14<"] = "pz_wall_nature_bush",
		[">11:14<"] = "pz_wall_nature_bush",
		[">6:13<"] = "pz_wall_nature_bush",
		[">14:7<"] = "pz_wall_nature_bush",
		[">14:9<"] = "pz_wall_nature_bush",
		[">11:4<"] = "pz_wall_nature_bush",
		[">15:7<"] = "pz_wall_nature_bush",
		[">15:5<"] = "pz_wall_nature_bush",
		[">19:13<"] = "pz_wall_desert_des_cactus",
		[">18:8<"] = "pz_wall_nature_bush",
		[">8:14<"] = "pz_wall_nature_bush",
		[">17:6<"] = "pz_wall_nature_bush",
		[">15:11<"] = "pz_wall_nature_bush",
		[">6:6<"] = "pz_wall_nature_bush",
		[">18:14<"] = "pz_wall_nature_bush",
		[">14:8<"] = "pz_wall_nature_bush",
		[">7:4<"] = "pz_wall_nature_bush",
		[">16:14<"] = "pz_wall_nature_bush",
		[">13:1<"] = "pz_wall_nature_bush",
		[">15:1<"] = "pz_wall_nature_bush",
		[">17:1<"] = "pz_wall_nature_bush",
		[">19:12<"] = "pz_wall_desert_des_cactus"
	            },
	["title"] = "\67\97\110\32\121\111\117\32\102\101\101\108\32\105\116\63",
	["reqballs"] = 11,
	["falling"] = {},
	["obstacles"] = {
		[">10:8<"] = "zzzglass",
		[">9:3<"] = "zzzglass",
		[">15:10<"] = "zzzglass",
		[">12:13<"] = "zzzglass",
		[">12:5<"] = "zzzglass",
		[">10:4<"] = "zzzglass",
		[">9:11<"] = "zzzglass",
		[">9:12<"] = "zzzglass",
		[">9:5<"] = "zzzglass",
		[">15:8<"] = "zzzglass",
		[">10:11<"] = "zzzglass",
		[">9:7<"] = "zzzglass",
		[">9:4<"] = "zzzglass",
		[">9:8<"] = "zzzglass",
		[">9:6<"] = "zzzglass",
		[">10:6<"] = "zzzglass",
		[">17:10<"] = "zzzglass",
		[">10:13<"] = "zzzglass",
		[">13:13<"] = "zzzglass",
		[">17:9<"] = "zzzglass",
		[">9:10<"] = "zzzglass",
		[">16:10<"] = "zzzglass",
		[">8:5<"] = "zzzglass",
		[">17:8<"] = "zzzglass",
		[">10:5<"] = "zzzglass",
		[">9:9<"] = "zzzglass",
		[">15:9<"] = "zzzglass",
		[">11:13<"] = "zzzglass",
		[">10:12<"] = "zzzglass",
		[">10:3<"] = "zzzglass",
		[">16:8<"] = "zzzglass",
		[">11:12<"] = "zzzglass",
		[">14:13<"] = "zzzglass",
		[">11:5<"] = "zzzglass",
		[">10:9<"] = "zzzglass",
		[">16:9<"] = "a_exit",
		[">7:5<"] = "zzzglass",
		[">10:10<"] = "zzzglass",
		[">10:7<"] = "zzzglass"
	                },
	["ghostwomen"] = {},
	["objects"] = {
		[2] = {
			["y"] = 12,
			["x"] = 8,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[5] = {
			["y"] = 6,
			["x"] = 11,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[11] = {
			["y"] = 2,
			["x"] = 16,
			["dir"] = "R",
			["kind"] = "ball"
		       },
		[4] = {
			["y"] = 6,
			["x"] = 8,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[10] = {
			["y"] = 13,
			["x"] = 16,
			["dir"] = "R",
			["kind"] = "ball"
		       },
		[9] = {
			["y"] = 12,
			["x"] = 16,
			["dir"] = "R",
			["kind"] = "ball"
		      },
		[8] = {
			["y"] = 12,
			["x"] = 11,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[3] = {
			["y"] = 6,
			["x"] = 7,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[7] = {
			["y"] = 12,
			["x"] = 12,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[1] = {
			["y"] = 12,
			["x"] = 7,
			["dir"] = "D",
			["kind"] = "ball"
		      },
		[6] = {
			["y"] = 6,
			["x"] = 12,
			["dir"] = "D",
			["kind"] = "ball"
		      }
	              }
       }


ret2 = {
	["tab"] = "settings",
	["strip"] = {
		["wall"] = {
			["cstrip"] = "pink",
			["tile"] = "pz_wall_nature_bush"
		           },
		["floor"] = {
			["cstrip"] = "nature",
			["tile"] = "pz_floor_nature_untitled"
		            },
		["plates"] = {
			["tile"] = "zzzglass"
		             },
		["exits"] = {
			["tile"] = "a_exit"
		            }
	            },
	["odir"] = 4
       }




return ret1, ret2


