--[[
	BallPlay Cupid
	Puzzle 35
	
	
	
	(c) Jeroen P. Broks, 2016, All rights reserved
	
		This program is free software: you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.
		
		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
		You should have received a copy of the GNU General Public License
		along with this program.  If not, see <http://www.gnu.org/licenses/>.
		
	Exceptions to the standard GNU license are available with Jeroen's written permission given prior 
	to the project the exceptions are needed for.
Version: 16.04.27
]]

  -- This file has been generated by BallPlay Cupid.
  -- and may only be used in combination with that game
  -- and in unmodified form. 
  -- unless stated otherwise in the game license.


local ret1, ret2



ret1 = {
	["format"] = {
		[1] = 25,
		[2] = 15
	             },
	["mission"] = "Collect",
	["partime"] = 0,
	["missionnum"] = 5,
	["background"] = "space",
	["title"] = "The Collector",
	["reqballs"] = 5,
	["floors"] = {
		[">8:10<"] = "pz_floor_modern_bluegrey",
		[">18:5<"] = "pz_floor_modern_bluegrey2",
		[">9:2<"] = "pz_floor_modern_bluegrey",
		[">11:4<"] = "pz_floor_modern_bluegrey",
		[">18:10<"] = "pz_floor_modern_bluegrey",
		[">16:1<"] = "pz_floor_modern_bluegrey",
		[">10:5<"] = "pz_floor_modern_bluegrey2",
		[">14:3<"] = "pz_floor_modern_bluegrey",
		[">7:2<"] = "pz_floor_modern_bluegrey",
		[">8:4<"] = "pz_floor_modern_bluegrey",
		[">17:1<"] = "pz_floor_modern_bluegrey",
		[">7:10<"] = "pz_floor_modern_bluegrey",
		[">7:1<"] = "pz_floor_modern_bluegrey",
		[">10:9<"] = "pz_floor_modern_bluegrey",
		[">8:6<"] = "pz_floor_modern_bluegrey2",
		[">13:9<"] = "pz_floor_modern_bluegrey",
		[">13:6<"] = "pz_floor_modern_bluegrey2",
		[">16:7<"] = "pz_floor_modern_bluegrey",
		[">17:9<"] = "pz_floor_modern_bluegrey",
		[">5:10<"] = "pz_floor_modern_bluegrey",
		[">13:3<"] = "pz_floor_modern_bluegrey",
		[">10:3<"] = "pz_floor_modern_bluegrey",
		[">7:7<"] = "pz_floor_modern_bluegrey",
		[">13:8<"] = "pz_floor_modern_bluegrey",
		[">16:3<"] = "pz_floor_modern_bluegrey",
		[">12:5<"] = "pz_floor_modern_bluegrey2",
		[">7:8<"] = "pz_floor_modern_bluegrey",
		[">8:2<"] = "pz_floor_modern_bluegrey",
		[">9:1<"] = "pz_floor_modern_bluegrey",
		[">17:8<"] = "pz_floor_modern_bluegrey",
		[">15:8<"] = "pz_floor_modern_bluegrey",
		[">9:7<"] = "pz_floor_modern_bluegrey",
		[">12:8<"] = "pz_floor_modern_bluegrey",
		[">15:3<"] = "pz_floor_modern_bluegrey",
		[">12:3<"] = "pz_floor_modern_bluegrey",
		[">7:4<"] = "pz_floor_modern_bluegrey",
		[">13:2<"] = "pz_floor_modern_bluegrey",
		[">11:10<"] = "pz_floor_modern_bluegrey",
		[">6:3<"] = "pz_floor_modern_bluegrey",
		[">12:6<"] = "pz_floor_modern_bluegrey2",
		[">5:4<"] = "pz_floor_modern_bluegrey",
		[">8:3<"] = "pz_floor_modern_bluegrey",
		[">6:5<"] = "pz_floor_modern_bluegrey2",
		[">8:5<"] = "pz_floor_modern_bluegrey2",
		[">15:5<"] = "pz_floor_modern_bluegrey2",
		[">9:10<"] = "pz_floor_modern_bluegrey",
		[">17:6<"] = "pz_floor_modern_bluegrey2",
		[">11:2<"] = "pz_floor_modern_bluegrey",
		[">11:5<"] = "pz_floor_modern_bluegrey2",
		[">12:2<"] = "pz_floor_modern_bluegrey",
		[">15:1<"] = "pz_floor_modern_bluegrey",
		[">5:7<"] = "pz_floor_modern_bluegrey",
		[">6:2<"] = "pz_floor_modern_bluegrey",
		[">5:6<"] = "pz_floor_modern_bluegrey2",
		[">13:7<"] = "pz_floor_modern_bluegrey",
		[">11:1<"] = "pz_floor_modern_bluegrey",
		[">15:6<"] = "pz_floor_modern_bluegrey2",
		[">6:7<"] = "pz_floor_modern_bluegrey",
		[">13:4<"] = "pz_floor_modern_bluegrey",
		[">14:5<"] = "pz_floor_modern_bluegrey2",
		[">7:3<"] = "pz_floor_modern_bluegrey",
		[">8:1<"] = "pz_floor_modern_bluegrey",
		[">18:4<"] = "pz_floor_modern_bluegrey",
		[">10:10<"] = "pz_floor_modern_bluegrey",
		[">5:1<"] = "pz_floor_modern_bluegrey",
		[">8:7<"] = "pz_floor_modern_bluegrey",
		[">15:2<"] = "pz_floor_modern_bluegrey",
		[">5:2<"] = "pz_floor_modern_bluegrey",
		[">4:5<"] = "pz_floor_modern_bluegrey",
		[">12:9<"] = "pz_floor_modern_bluegrey",
		[">11:6<"] = "pz_floor_modern_bluegrey2",
		[">18:3<"] = "pz_floor_modern_bluegrey",
		[">18:2<"] = "pz_floor_modern_bluegrey",
		[">16:10<"] = "pz_floor_modern_bluegrey",
		[">5:3<"] = "pz_floor_modern_bluegrey",
		[">17:4<"] = "pz_floor_modern_bluegrey",
		[">9:9<"] = "pz_floor_modern_bluegrey",
		[">10:2<"] = "pz_floor_modern_bluegrey",
		[">14:1<"] = "pz_floor_modern_bluegrey",
		[">7:5<"] = "pz_floor_modern_bluegrey2",
		[">10:8<"] = "pz_floor_modern_bluegrey",
		[">13:1<"] = "pz_floor_modern_bluegrey",
		[">4:6<"] = "pz_floor_modern_bluegrey",
		[">6:6<"] = "pz_floor_modern_bluegrey2",
		[">6:4<"] = "pz_floor_modern_bluegrey",
		[">12:4<"] = "pz_floor_modern_bluegrey",
		[">6:10<"] = "pz_floor_modern_bluegrey",
		[">7:9<"] = "pz_floor_modern_bluegrey",
		[">17:5<"] = "pz_floor_modern_bluegrey2",
		[">17:3<"] = "pz_floor_modern_bluegrey",
		[">16:2<"] = "pz_floor_modern_bluegrey",
		[">15:10<"] = "pz_floor_modern_bluegrey",
		[">9:3<"] = "pz_floor_modern_bluegrey",
		[">16:5<"] = "pz_floor_modern_bluegrey2",
		[">14:8<"] = "pz_floor_modern_bluegrey",
		[">5:5<"] = "pz_floor_modern_bluegrey2",
		[">9:5<"] = "pz_floor_modern_bluegrey2",
		[">15:9<"] = "pz_floor_modern_bluegrey",
		[">15:4<"] = "pz_floor_modern_bluegrey",
		[">10:4<"] = "pz_floor_modern_bluegrey",
		[">14:4<"] = "pz_floor_modern_bluegrey",
		[">6:9<"] = "pz_floor_modern_bluegrey",
		[">16:4<"] = "pz_floor_modern_bluegrey",
		[">9:4<"] = "pz_floor_modern_bluegrey",
		[">16:6<"] = "pz_floor_modern_bluegrey2",
		[">13:10<"] = "pz_floor_modern_bluegrey",
		[">9:6<"] = "pz_floor_modern_bluegrey2",
		[">18:9<"] = "pz_floor_modern_bluegrey",
		[">19:5<"] = "pz_floor_modern_bluegrey",
		[">12:7<"] = "pz_floor_modern_bluegrey",
		[">5:9<"] = "pz_floor_modern_bluegrey",
		[">10:6<"] = "pz_floor_modern_bluegrey2",
		[">14:6<"] = "pz_floor_modern_bluegrey2",
		[">16:9<"] = "pz_floor_modern_bluegrey",
		[">17:7<"] = "pz_floor_modern_bluegrey",
		[">16:8<"] = "pz_floor_modern_bluegrey",
		[">18:7<"] = "pz_floor_modern_bluegrey",
		[">8:9<"] = "pz_floor_modern_bluegrey",
		[">11:3<"] = "pz_floor_modern_bluegrey",
		[">6:8<"] = "pz_floor_modern_bluegrey",
		[">11:8<"] = "pz_floor_modern_bluegrey",
		[">11:7<"] = "pz_floor_modern_bluegrey",
		[">14:10<"] = "pz_floor_modern_bluegrey",
		[">19:6<"] = "pz_floor_modern_bluegrey",
		[">12:1<"] = "pz_floor_modern_bluegrey",
		[">8:8<"] = "pz_floor_modern_bluegrey",
		[">6:1<"] = "pz_floor_modern_bluegrey",
		[">18:1<"] = "pz_floor_modern_bluegrey",
		[">15:7<"] = "pz_floor_modern_bluegrey",
		[">14:9<"] = "pz_floor_modern_bluegrey",
		[">11:9<"] = "pz_floor_modern_bluegrey",
		[">18:8<"] = "pz_floor_modern_bluegrey",
		[">17:10<"] = "pz_floor_modern_bluegrey",
		[">10:7<"] = "pz_floor_modern_bluegrey",
		[">12:10<"] = "pz_floor_modern_bluegrey",
		[">17:2<"] = "pz_floor_modern_bluegrey",
		[">10:1<"] = "pz_floor_modern_bluegrey",
		[">18:6<"] = "pz_floor_modern_bluegrey2",
		[">7:6<"] = "pz_floor_modern_bluegrey2",
		[">9:8<"] = "pz_floor_modern_bluegrey",
		[">5:8<"] = "pz_floor_modern_bluegrey",
		[">13:5<"] = "pz_floor_modern_bluegrey2",
		[">14:2<"] = "pz_floor_modern_bluegrey",
		[">14:7<"] = "pz_floor_modern_bluegrey"
	             },
	["walls"] = {
		[">17:0<"] = "pz_wall_modern_s",
		[">4:1<"] = "pz_wall_modern_w",
		[">19:4<"] = "pz_wall_modern_nes",
		[">4:2<"] = "pz_wall_modern_w",
		[">19:11<"] = "pz_wall_modern_se",
		[">9:11<"] = "pz_wall_modern_n",
		[">5:11<"] = "pz_wall_modern_n",
		[">20:4<"] = "pz_wall_modern_ne",
		[">13:0<"] = "pz_wall_modern_s",
		[">16:11<"] = "pz_wall_modern_n",
		[">10:11<"] = "pz_wall_modern_n",
		[">19:3<"] = "pz_wall_modern_e",
		[">3:5<"] = "pz_wall_modern_w",
		[">16:0<"] = "pz_wall_modern_s",
		[">18:0<"] = "pz_wall_modern_s",
		[">4:3<"] = "pz_wall_modern_w",
		[">18:11<"] = "pz_wall_modern_n",
		[">19:1<"] = "pz_wall_modern_e",
		[">20:6<"] = "pz_wall_modern_e",
		[">4:8<"] = "pz_wall_modern_w",
		[">17:11<"] = "pz_wall_modern_n",
		[">7:11<"] = "pz_wall_modern_n",
		[">8:11<"] = "pz_wall_modern_n",
		[">12:0<"] = "pz_wall_modern_s",
		[">8:0<"] = "pz_wall_modern_s",
		[">19:10<"] = "pz_wall_modern_e",
		[">12:11<"] = "pz_wall_modern_n",
		[">3:6<"] = "pz_wall_modern_w",
		[">4:9<"] = "pz_wall_modern_w",
		[">19:9<"] = "pz_wall_modern_e",
		[">4:7<"] = "pz_wall_modern_sws",
		[">11:0<"] = "pz_wall_modern_s",
		[">6:11<"] = "pz_wall_modern_n",
		[">19:8<"] = "pz_wall_modern_e",
		[">13:11<"] = "pz_wall_modern_n",
		[">3:7<"] = "pz_wall_modern_sw",
		[">4:11<"] = "pz_wall_modern_sw",
		[">20:5<"] = "pz_wall_modern_e",
		[">19:0<"] = "pz_wall_modern_ne",
		[">5:0<"] = "pz_wall_modern_s",
		[">4:4<"] = "pz_wall_modern_nws",
		[">6:0<"] = "pz_wall_modern_s",
		[">11:11<"] = "pz_wall_modern_n",
		[">14:11<"] = "pz_wall_modern_n",
		[">10:0<"] = "pz_wall_modern_s",
		[">9:0<"] = "pz_wall_modern_s",
		[">15:11<"] = "pz_wall_modern_n",
		[">4:0<"] = "pz_wall_modern_nw",
		[">20:7<"] = "pz_wall_modern_se",
		[">19:2<"] = "pz_wall_modern_e",
		[">7:0<"] = "pz_wall_modern_s",
		[">3:4<"] = "pz_wall_modern_nw",
		[">19:7<"] = "pz_wall_modern_ses",
		[">14:0<"] = "pz_wall_modern_s",
		[">15:0<"] = "pz_wall_modern_s",
		[">4:10<"] = "pz_wall_modern_w"
	            },
	["music"] = "MUSIC/THEME/URBAN-JUNGLE-2061.MP3",
	["tools"] = {
		["plate2"] = 100,
		["plate1"] = 100,
		["trash"] = 100,
		["barrier"] = 0
	            },
	["falling"] = {},
	["ghostwomen"] = {},
	["obstacles"] = {
		[">5:7<"] = "bb01",
		[">12:1<"] = "dot",
		[">5:6<"] = "dot",
		[">13:7<"] = "bb01",
		[">11:1<"] = "dot",
		[">5:9<"] = "platelaser_blue",
		[">6:7<"] = "bb01",
		[">13:4<"] = "bb05",
		[">11:4<"] = "bb05",
		[">13:5<"] = "dot",
		[">14:5<"] = "dot",
		[">16:1<"] = "dot",
		[">10:5<"] = "dot",
		[">8:1<"] = "dot",
		[">18:4<"] = "bb05",
		[">8:4<"] = "bb05",
		[">5:1<"] = "dot",
		[">6:6<"] = "dot",
		[">19:5<"] = "laser_Left_green",
		[">7:1<"] = "dot",
		[">8:6<"] = "dot",
		[">13:9<"] = "platelaser_ember",
		[">13:6<"] = "dot",
		[">11:6<"] = "dot",
		[">16:7<"] = "bb01",
		[">17:5<"] = "dot",
		[">17:4<"] = "bb05",
		[">10:2<"] = "platelaser_green",
		[">14:1<"] = "dot",
		[">7:5<"] = "dot",
		[">7:7<"] = "bb01",
		[">10:7<"] = "bb01",
		[">12:4<"] = "bb05",
		[">12:5<"] = "dot",
		[">10:4<"] = "bb05",
		[">16:5<"] = "dot",
		[">9:1<"] = "dot",
		[">9:5<"] = "dot",
		[">15:4<"] = "bb05",
		[">9:7<"] = "bb01",
		[">18:6<"] = "dot",
		[">9:4<"] = "bb05",
		[">16:6<"] = "dot",
		[">13:2<"] = "platelaser_red",
		[">9:6<"] = "dot",
		[">7:6<"] = "dot",
		[">14:4<"] = "bb05",
		[">5:5<"] = "dot",
		[">4:6<"] = "laser_Right_ember",
		[">10:6<"] = "dot",
		[">14:6<"] = "dot",
		[">18:1<"] = "dot",
		[">12:6<"] = "dot",
		[">17:7<"] = "bb01",
		[">5:4<"] = "bb05",
		[">18:9<"] = "platelaser_green",
		[">6:1<"] = "dot",
		[">18:5<"] = "dot",
		[">6:5<"] = "dot",
		[">11:7<"] = "bb01",
		[">12:7<"] = "bb01",
		[">19:6<"] = "laser_Left_red",
		[">8:7<"] = "bb01",
		[">17:1<"] = "dot",
		[">4:5<"] = "laser_Right_blue",
		[">8:5<"] = "dot",
		[">15:7<"] = "bb01",
		[">15:5<"] = "dot",
		[">16:4<"] = "bb05",
		[">8:9<"] = "platelaser_red",
		[">18:7<"] = "bb01",
		[">17:6<"] = "dot",
		[">11:2<"] = "platelaser_blue",
		[">7:4<"] = "bb05",
		[">13:1<"] = "dot",
		[">10:1<"] = "dot",
		[">11:5<"] = "dot",
		[">6:4<"] = "bb05",
		[">12:2<"] = "platelaser_ember",
		[">15:1<"] = "dot",
		[">15:6<"] = "dot",
		[">14:7<"] = "bb01"
	                },
	["objects"] = {
		[8] = {
			["y"] = 9,
			["x"] = 6,
			["kind"] = "ball",
			["dir"] = "E"
		      },
		[2] = {
			["y"] = 2,
			["x"] = 18,
			["kind"] = "ghostgreen",
			["dir"] = "L"
		      },
		[5] = {
			["y"] = 10,
			["x"] = 18,
			["kind"] = "ballgreen",
			["dir"] = "L"
		      },
		[3] = {
			["y"] = 10,
			["x"] = 5,
			["kind"] = "ballember",
			["dir"] = "E"
		      },
		[7] = {
			["y"] = 9,
			["x"] = 17,
			["kind"] = "ball",
			["dir"] = "L"
		      },
		[1] = {
			["y"] = 2,
			["x"] = 5,
			["kind"] = "ghostblue",
			["dir"] = "E"
		      },
		[4] = {
			["y"] = 8,
			["x"] = 5,
			["kind"] = "ballblue",
			["dir"] = "E"
		      },
		[6] = {
			["y"] = 8,
			["x"] = 18,
			["kind"] = "ballred",
			["dir"] = "L"
		      }
	              }
       }


ret2 = {
	["tab"] = "settings",
	["strip"] = {
		["plates"] = {
			["tile"] = "gplate1"
		             },
		["lasers"] = {
			["tile"] = "platelaser_ember"
		             },
		["wall"] = {
			["cstrip"] = "modern",
			["tile"] = "pz_wall_modern_ne"
		           },
		["floor"] = {
			["cstrip"] = "modern",
			["tile"] = "pz_floor_modern_bluegrey"
		            },
		["breakblocks"] = {
			["tile"] = "dot"
		                  }
	            },
	["odir"] = 3
       }




return ret1, ret2


