--[[
	BallPlay Cupid
	Puzzle 43
	
	
	
	(c) Jeroen P. Broks, 2016, All rights reserved
	
		This program is free software: you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.
		
		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
		You should have received a copy of the GNU General Public License
		along with this program.  If not, see <http://www.gnu.org/licenses/>.
		
	Exceptions to the standard GNU license are available with Jeroen's written permission given prior 
	to the project the exceptions are needed for.
Version: 16.05.17
]]

  -- This file has been generated by BallPlay Cupid.
  -- and may only be used in combination with that game
  -- and in unmodified form. 
  -- unless stated otherwise in the game license.


local ret1, ret2



ret1 = {
	["format"] = {
		[2] = 15,
		[1] = 25
	             },
	["partime"] = 0,
	["floors"] = {
		[">5:7<"] = "pz_floor_graveyard_grass",
		[">12:1<"] = "pz_floor_graveyard_grass",
		[">5:6<"] = "pz_floor_graveyard_grass",
		[">13:7<"] = "pz_floor_graveyard_grass",
		[">11:1<"] = "pz_floor_graveyard_grass",
		[">4:1<"] = "pz_floor_graveyard_grass",
		[">9:2<"] = "pz_floor_graveyard_grass",
		[">6:7<"] = "pz_floor_graveyard_grass",
		[">3:11<"] = "pz_floor_graveyard_grass",
		[">1:4<"] = "pz_floor_graveyard_grass",
		[">9:11<"] = "pz_floor_graveyard_grass",
		[">6:1<"] = "pz_floor_graveyard_grass",
		[">16:1<"] = "pz_floor_graveyard_grass",
		[">10:5<"] = "pz_floor_graveyard_grass",
		[">8:1<"] = "pz_floor_graveyard_grass",
		[">10:11<"] = "pz_floor_graveyard_grass",
		[">8:4<"] = "pz_floor_graveyard_grass",
		[">5:1<"] = "pz_floor_graveyard_grass",
		[">8:7<"] = "pz_floor_graveyard_grass",
		[">7:11<"] = "pz_floor_graveyard_grass",
		[">8:11<"] = "pz_floor_graveyard_grass",
		[">7:1<"] = "pz_floor_graveyard_grass",
		[">16:11<"] = "pz_floor_graveyard_grass",
		[">8:6<"] = "pz_floor_graveyard_grass",
		[">13:11<"] = "pz_floor_graveyard_grass",
		[">4:5<"] = "pz_floor_graveyard_grass",
		[">13:6<"] = "pz_floor_graveyard_grass",
		[">6:11<"] = "pz_floor_graveyard_grass",
		[">16:7<"] = "pz_floor_graveyard_grass",
		[">2:1<"] = "pz_floor_graveyard_grass",
		[">16:10<"] = "pz_floor_graveyard_grass",
		[">14:11<"] = "pz_floor_graveyard_grass",
		[">11:11<"] = "pz_floor_graveyard_grass",
		[">14:1<"] = "pz_floor_graveyard_grass",
		[">7:5<"] = "pz_floor_graveyard_grass",
		[">4:11<"] = "pz_floor_graveyard_grass",
		[">7:7<"] = "pz_floor_graveyard_grass",
		[">13:1<"] = "pz_floor_graveyard_grass",
		[">1:1<"] = "pz_floor_graveyard_grass",
		[">16:3<"] = "pz_floor_graveyard_grass",
		[">1:9<"] = "pz_floor_graveyard_grass",
		[">12:5<"] = "pz_floor_graveyard_grass",
		[">1:10<"] = "pz_floor_graveyard_grass",
		[">16:2<"] = "pz_floor_graveyard_grass",
		[">16:5<"] = "pz_floor_graveyard_grass",
		[">5:11<"] = "pz_floor_graveyard_grass",
		[">9:5<"] = "pz_floor_graveyard_grass",
		[">9:7<"] = "pz_floor_graveyard_grass",
		[">9:4<"] = "pz_floor_graveyard_grass",
		[">16:6<"] = "pz_floor_graveyard_grass",
		[">9:6<"] = "pz_floor_graveyard_grass",
		[">12:7<"] = "pz_floor_graveyard_grass",
		[">9:3<"] = "pz_floor_graveyard_grass",
		[">10:6<"] = "pz_floor_graveyard_grass",
		[">10:1<"] = "pz_floor_graveyard_grass",
		[">12:11<"] = "pz_floor_graveyard_grass",
		[">12:6<"] = "pz_floor_graveyard_grass",
		[">1:8<"] = "pz_floor_graveyard_grass",
		[">1:11<"] = "pz_floor_graveyard_grass",
		[">1:5<"] = "pz_floor_graveyard_grass",
		[">8:3<"] = "pz_floor_graveyard_grass",
		[">1:3<"] = "pz_floor_graveyard_grass",
		[">6:5<"] = "pz_floor_graveyard_grass",
		[">4:6<"] = "pz_floor_graveyard_grass",
		[">1:6<"] = "pz_floor_graveyard_grass",
		[">16:8<"] = "pz_floor_graveyard_grass",
		[">9:1<"] = "pz_floor_graveyard_grass",
		[">7:6<"] = "pz_floor_graveyard_grass",
		[">3:1<"] = "pz_floor_graveyard_grass",
		[">8:5<"] = "pz_floor_graveyard_grass",
		[">1:7<"] = "pz_floor_graveyard_grass",
		[">8:2<"] = "pz_floor_graveyard_grass",
		[">16:4<"] = "pz_floor_graveyard_grass",
		[">4:7<"] = "pz_floor_graveyard_grass",
		[">5:5<"] = "pz_floor_graveyard_grass",
		[">1:2<"] = "pz_floor_graveyard_grass",
		[">15:11<"] = "pz_floor_graveyard_grass",
		[">6:6<"] = "pz_floor_graveyard_grass",
		[">2:11<"] = "pz_floor_graveyard_grass",
		[">10:7<"] = "pz_floor_graveyard_grass",
		[">11:5<"] = "pz_floor_graveyard_grass",
		[">11:6<"] = "pz_floor_graveyard_grass",
		[">16:9<"] = "pz_floor_graveyard_grass",
		[">15:1<"] = "pz_floor_graveyard_grass",
		[">13:5<"] = "pz_floor_graveyard_grass",
		[">11:7<"] = "pz_floor_graveyard_grass"
	             },
	["falling"] = {},
	["ghostwomen"] = {},
	["mission"] = "Normal",
	["walls"] = {
		[">6:2<"] = "pz_wall_dungeon_southwall2",
		[">6:4<"] = "pz_wall_dungeon_backwall2",
		[">12:12<"] = "pz_wall_dungeon_southwall2",
		[">15:6<"] = "pz_wall_dungeon_westwall2",
		[">0:1<"] = "pz_wall_dungeon_westwall2",
		[">15:12<"] = "pz_wall_dungeon_southwall2",
		[">13:4<"] = "pz_wall_dungeon_backwall2",
		[">11:4<"] = "pz_wall_dungeon_backwall2",
		[">5:12<"] = "pz_wall_dungeon_southwall2",
		[">13:0<"] = "pz_wall_dungeon_backwall2",
		[">14:5<"] = "pz_wall_dungeon_eastwall2",
		[">4:2<"] = "pz_wall_dungeon_southwall2",
		[">2:8<"] = "pz_wall_dungeon_eastwall2",
		[">0:3<"] = "pz_wall_dungeon_westwall2",
		[">4:0<"] = "pz_wall_dungeon_backwall2",
		[">0:5<"] = "pz_wall_dungeon_westwall2",
		[">14:3<"] = "pz_wall_dungeon_eastwall2",
		[">5:8<"] = "pz_wall_dungeon_southwall2",
		[">3:3<"] = "pz_wall_dungeon_westwall2",
		[">10:10<"] = "pz_wall_dungeon_backwall2",
		[">0:4<"] = "pz_wall_dungeon_westwall2",
		[">14:4<"] = "pz_wall_dungeon_eastwall2",
		[">1:0<"] = "pz_wall_dungeon_backwall2",
		[">7:8<"] = "pz_wall_dungeon_southwall2",
		[">17:1<"] = "pz_wall_dungeon_eastwall2",
		[">15:2<"] = "pz_wall_dungeon_sw_bigcorner2",
		[">4:12<"] = "pz_wall_dungeon_southwall2",
		[">3:7<"] = "pz_wall_dungeon_westwall2",
		[">3:2<"] = "pz_wall_dungeon_southwall2",
		[">5:2<"] = "pz_wall_dungeon_southwall2",
		[">9:12<"] = "pz_wall_dungeon_southwall2",
		[">12:0<"] = "pz_wall_dungeon_backwall2",
		[">6:8<"] = "pz_wall_dungeon_southwall2",
		[">9:0<"] = "pz_wall_dungeon_backwall2",
		[">1:12<"] = "pz_wall_dungeon_southwall2",
		[">11:0<"] = "pz_wall_dungeon_backwall2",
		[">5:0<"] = "pz_wall_dungeon_backwall2",
		[">6:0<"] = "pz_wall_dungeon_backwall2",
		[">5:4<"] = "pz_wall_dungeon_backwall2",
		[">17:5<"] = "pz_wall_dungeon_eastwall2",
		[">11:8<"] = "pz_wall_dungeon_southwall2",
		[">6:12<"] = "pz_wall_dungeon_southwall2",
		[">14:10<"] = "pz_wall_dungeon_backwall2",
		[">17:3<"] = "pz_wall_dungeon_eastwall2",
		[">4:4<"] = "pz_wall_dungeon_backwall2",
		[">3:5<"] = "pz_wall_dungeon_westwall2",
		[">11:2<"] = "pz_wall_dungeon_southwall2",
		[">6:10<"] = "pz_wall_dungeon_backwall2",
		[">14:0<"] = "pz_wall_dungeon_backwall2",
		[">10:2<"] = "pz_wall_dungeon_se_bigcorner2",
		[">3:6<"] = "pz_wall_dungeon_westwall2",
		[">0:10<"] = "pz_wall_dungeon_westwall2",
		[">8:0<"] = "pz_wall_dungeon_backwall2",
		[">0:2<"] = "pz_wall_dungeon_westwall2",
		[">7:0<"] = "pz_wall_dungeon_backwall2",
		[">3:4<"] = "pz_wall_dungeon_westwall2",
		[">2:3<"] = "pz_wall_dungeon_eastwall2",
		[">7:4<"] = "pz_wall_dungeon_backwall3",
		[">2:5<"] = "pz_wall_dungeon_eastwall2",
		[">4:10<"] = "pz_wall_dungeon_backwall3",
		[">10:8<"] = "pz_wall_dungeon_southwall2",
		[">13:8<"] = "pz_wall_dungeon_southwall2",
		[">2:6<"] = "pz_wall_dungeon_eastwall2",
		[">7:2<"] = "pz_wall_dungeon_sw_bigcorner2",
		[">12:4<"] = "pz_wall_dungeon_backwall2",
		[">2:10<"] = "pz_wall_dungeon_backwall2",
		[">8:10<"] = "pz_wall_dungeon_backwall2",
		[">14:2<"] = "pz_wall_dungeon_southwall2",
		[">2:12<"] = "pz_wall_dungeon_southwall2",
		[">10:4<"] = "pz_wall_dungeon_backwall3",
		[">15:8<"] = "pz_wall_dungeon_westwall2",
		[">5:10<"] = "pz_wall_dungeon_backwall2",
		[">16:12<"] = "pz_wall_dungeon_southwall2",
		[">2:0<"] = "pz_wall_dungeon_backwall2",
		[">17:7<"] = "pz_wall_dungeon_eastwall2",
		[">13:12<"] = "pz_wall_dungeon_southwall2",
		[">17:0<"] = "pz_wall_dungeon_eastwall2",
		[">15:9<"] = "pz_wall_dungeon_westwall2",
		[">15:4<"] = "pz_wall_dungeon_westwall2",
		[">16:0<"] = "pz_wall_dungeon_backwall2",
		[">3:12<"] = "pz_wall_dungeon_southwall2",
		[">17:11<"] = "pz_wall_dungeon_eastwall2",
		[">17:2<"] = "pz_wall_dungeon_eastwall2",
		[">17:4<"] = "pz_wall_dungeon_eastwall2",
		[">10:0<"] = "pz_wall_dungeon_backwall2",
		[">13:10<"] = "pz_wall_dungeon_backwall3",
		[">11:10<"] = "pz_wall_dungeon_backwall2",
		[">3:10<"] = "pz_wall_dungeon_backwall2",
		[">0:0<"] = "pz_wall_dungeon_westwall2",
		[">4:8<"] = "pz_wall_dungeon_southwall2",
		[">13:2<"] = "pz_wall_dungeon_southwall2",
		[">9:8<"] = "pz_wall_dungeon_southwall2",
		[">14:6<"] = "pz_wall_dungeon_eastwall2",
		[">15:3<"] = "pz_wall_dungeon_westwall2",
		[">8:12<"] = "pz_wall_dungeon_southwall2",
		[">12:8<"] = "pz_wall_dungeon_southwall2",
		[">2:2<"] = "pz_wall_dungeon_se_bigcorner2",
		[">2:4<"] = "pz_wall_dungeon_eastwall2",
		[">14:12<"] = "pz_wall_dungeon_southwall2",
		[">2:7<"] = "pz_wall_dungeon_eastwall2",
		[">17:8<"] = "pz_wall_dungeon_eastwall2",
		[">0:9<"] = "pz_wall_dungeon_westwall2",
		[">10:12<"] = "pz_wall_dungeon_southwall2",
		[">17:9<"] = "pz_wall_dungeon_eastwall2",
		[">17:10<"] = "pz_wall_dungeon_eastwall2",
		[">8:8<"] = "pz_wall_dungeon_southwall2",
		[">3:0<"] = "pz_wall_dungeon_backwall3",
		[">15:10<"] = "pz_wall_dungeon_backwall2",
		[">15:7<"] = "pz_wall_dungeon_westwall2",
		[">15:5<"] = "pz_wall_dungeon_westwall2",
		[">9:10<"] = "pz_wall_dungeon_backwall2",
		[">0:11<"] = "pz_wall_dungeon_westwall2",
		[">0:7<"] = "pz_wall_dungeon_westwall2",
		[">17:6<"] = "pz_wall_dungeon_eastwall2",
		[">12:10<"] = "pz_wall_dungeon_backwall2",
		[">2:9<"] = "pz_wall_dungeon_eastwall2",
		[">11:12<"] = "pz_wall_dungeon_southwall2",
		[">0:8<"] = "pz_wall_dungeon_westwall2",
		[">0:6<"] = "pz_wall_dungeon_westwall2",
		[">7:12<"] = "pz_wall_dungeon_southwall2",
		[">12:2<"] = "pz_wall_dungeon_southwall2",
		[">7:10<"] = "pz_wall_dungeon_backwall2",
		[">15:0<"] = "pz_wall_dungeon_backwall3",
		[">14:7<"] = "pz_wall_dungeon_eastwall2"
	            },
	["title"] = "Perfect Timing",
	["obstacles"] = {
		[">1:11<"] = "zzarrow_droid_up",
		[">16:11<"] = "zzarrow_droid_left",
		[">10:11<"] = "a_exit",
		[">1:1<"] = "zzarrow_droid_right",
		[">7:11<"] = "a_exit",
		[">16:1<"] = "zzarrow_droid_down"
	                },
	["reqballs"] = 1,
	["tools"] = {
		["plate2"] = 100,
		["plate1"] = 100,
		["trash"] = 100,
		["barrier"] = 0
	            },
	["missionnum"] = 1,
	["objects"] = {
		[14] = {
			["y"] = 7,
			["x"] = 12,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[2] = {
			["y"] = 7,
			["x"] = 16,
			["kind"] = "robot",
			["dir"] = "D"
		      },
		[12] = {
			["y"] = 7,
			["x"] = 11,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[11] = {
			["y"] = 7,
			["x"] = 10,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[10] = {
			["y"] = 1,
			["x"] = 13,
			["kind"] = "robot",
			["dir"] = "E"
		       },
		[9] = {
			["y"] = 1,
			["x"] = 4,
			["kind"] = "robot",
			["dir"] = "E"
		      },
		[8] = {
			["y"] = 3,
			["x"] = 1,
			["kind"] = "robot",
			["dir"] = "U"
		      },
		[7] = {
			["y"] = 9,
			["x"] = 1,
			["kind"] = "robot",
			["dir"] = "U"
		      },
		[1] = {
			["y"] = 2,
			["x"] = 16,
			["kind"] = "robot",
			["dir"] = "D"
		      },
		[6] = {
			["y"] = 11,
			["x"] = 3,
			["kind"] = "robot",
			["dir"] = "L"
		      },
		[5] = {
			["y"] = 11,
			["x"] = 8,
			["kind"] = "robot",
			["dir"] = "L"
		      },
		[4] = {
			["y"] = 11,
			["x"] = 14,
			["kind"] = "robot",
			["dir"] = "L"
		      },
		[18] = {
			["y"] = 7,
			["x"] = 4,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[3] = {
			["y"] = 10,
			["x"] = 16,
			["kind"] = "robot",
			["dir"] = "D"
		      },
		[17] = {
			["y"] = 7,
			["x"] = 5,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[16] = {
			["y"] = 7,
			["x"] = 6,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[15] = {
			["y"] = 7,
			["x"] = 7,
			["kind"] = "ball",
			["dir"] = "U"
		       },
		[13] = {
			["y"] = 7,
			["x"] = 13,
			["kind"] = "ball",
			["dir"] = "U"
		       }
	              }
       }


ret2 = {
	["tab"] = "settings",
	["strip"] = {
		["wall"] = {
			["cstrip"] = "dungeon",
			["tile"] = "pz_wall_dungeon_southwall2"
		           },
		["exits"] = {
			["tile"] = "a_exit"
		            },
		["plates"] = {
			["tile"] = "zzarrow_droid_right"
		             },
		["lasers"] = {
			["tile"] = "laser_Down_blue"
		             },
		["floor"] = {
			["cstrip"] = "graveyard",
			["tile"] = "pz_floor_graveyard_grass"
		            },
		["breakblocks"] = {
			["tile"] = "bb01"
		                  }
	            },
	["odir"] = 4
       }




return ret1, ret2


